---
- name: update php
  hosts: all
  tasks:
      shell: |
        sed -i "s/lab-php:2.0/lab-php:3.0/g" /lab/php.yml
        kubectl apply -f /lab/php.yml
      when:
        - ansible_facts['hostname'] == 'master'
